### ISSUE TITLE
adapt plugin registry

### ISSUE THREAD

**Issue by oliverfoster** [jasonbutler/adapt-extension-plugins#1]
Hi Jason,

We're making an effort to clean up all of the Adapt Learning plugins because we can now unregister them - which is wholly new and exciting.

I'd like to re-register ``adapt-disableRightClick`` as the name doesn't match the GitHub repository name ``adapt-extension-plugins``. 

I realize that the different names may well be intentional or required but I thought I'd let you know we're making an effort.

I will leave ``adapt-disableRightClick`` as it is if I don't hear from you or if I do and you want it to stay as it is.

If you fancy, feel free to unregister, rename and re-register on your own, we'd really appreciate the testing as we've updated the registry's server and the command line client. If you do decide to give it a go yourself you will need the latest version of the ```adapt-cli``` by running ``npm -g install adapt-cli`` or ``npm -g update adapt-cli``.

I look forward to hearing from you.

Ollie.

**Comment by chris-steele** [comment]
@jasonbutler sorry to be the bearer of mildly bad news, but can you just hold fire on trying to unregister for a few days while some further tweaks are done? Thanks!
